[package]
name = "hello_remote_world"
version = "0.1.0"
edition = "2021"
authors = ["VS Code <vscode@microsoft.com>"]
[dependencies]
actix-web = "4"


[[bin]]
name = "hello_remote_world"
path = "test-project/src/main.rs"
